- hosts: all
  user: root
  sudo: true
  tasks:
    - name: Install Mariadb
      yum:
          name: mariadb-server
          state: latest
    - name: start mariadb
      service:
         name: mariadb
         state: started
    - name: Install epel
      yum:
          name: epel-release
          state: present
    - name: Install pip
      yum:
          name: python-pip
          state: present
    - name: Install pip
      yum:
          name: MySQL-python
          state: present
    - name: Set root Password
      mysql_user: login_password={{ 'mysql_root_password' }} check_implicit_admin=yes name=root host={{ item }} password={{ 'mysql_root_password' }} state=present 
      with_items:
        - localhost
        - 127.0.0.1
        - ::1
    - name: Remove anonymous users
      command: 'mysql -pmysql_root_password -ne  "{{ item }}"'
      with_items:
        - DELETE FROM mysql.user WHERE User=''
      changed_when: False
    - name: Reload privilege tables
      command: 'mysql -pmysql_root_password -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False
    - name: Disallow root login remotely
      command: 'mysql -pmysql_root_password -ne "{{ item }}"'
      with_items:
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
      changed_when: False

    - name: Remove test database and access to it
      command: 'mysql -pmysql_root_password -ne "{{ item }}"'
      with_items:
        - DROP DATABASE IF EXISTS test
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
      changed_when: False
    - name: Reload privilege tables
      command: 'mysql -pmysql_root_password -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES
      changed_when: False
    - name: creating DB and tables
      mysql_db:
          state: import
          name: all
          target: /root/scripts/dbs.sql
